name: asciidoctor github pages

on:
  push:
    branches:
      - 'feature/github-actions'

jobs:
  build:
    name: Build ⚙
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Docker
        run: |
          chmod a+x ./build-gh-actions.sh
          ./build-gh-actions.sh
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: gh-pages
          path: gh-pages
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: gh-pages
